//
//  IntervalOfUpdatingPresenter.swift
//  News
//
//  Created by Игорь on 31.01.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntervalOfUpdatingPresentationLogic {
    func presentSavedIntervalOfUpdating(response: IntervalOfUpdating.GetSavedIntervalOfUpdating.Response)
}

class IntervalOfUpdatingPresenter: IntervalOfUpdatingPresentationLogic {
    
    weak var viewController: IntervalOfUpdatingDisplayLogic?
    
    // MARK: Present saved interval of updating
    
    func presentSavedIntervalOfUpdating(response: IntervalOfUpdating.GetSavedIntervalOfUpdating.Response) {
        let viewModel = IntervalOfUpdating.GetSavedIntervalOfUpdating.ViewModel(hours: response.hours, minutes: response.minutes, seconds: response.seconds)
        viewController?.displaySavedIntervalOfUpdating(viewModel: viewModel)
    }
}
