//
//  IntervalOfUpdatingModels.swift
//  News
//
//  Created by Игорь on 31.01.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum IntervalOfUpdating {
    
    // MARK: Use cases
    
    enum SaveIntervalOfUpdating {
        struct Request {
            let seconds: Int
        }
    }
    
    enum GetSavedIntervalOfUpdating {
        struct Response {
            let (hours, minutes, seconds): (Int, Int, Int)
        }
        
        struct ViewModel {
            let (hours, minutes, seconds): (Int, Int, Int)
        }
    }
}
