//
//  IntervalOfUpdatingInteractor.swift
//  News
//
//  Created by Игорь on 31.01.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntervalOfUpdatingBusinessLogic {
    func saveIntervalOfUpdating(request: IntervalOfUpdating.SaveIntervalOfUpdating.Request)
}

protocol IntervalOfUpdatingDataStore {
    //var name: String { get set }
}

class IntervalOfUpdatingInteractor: IntervalOfUpdatingBusinessLogic, IntervalOfUpdatingDataStore {
    
    var presenter: IntervalOfUpdatingPresentationLogic?
    var worker: IntervalOfUpdatingWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func saveIntervalOfUpdating(request: IntervalOfUpdating.SaveIntervalOfUpdating.Request) {
        UserDefaultsStorageManager.shared.saveIntervalOfUpdatingIn(seconds: request.seconds)
    }
}
