//
//  IntervalOfUpdatingInteractor.swift
//  News
//
//  Created by Игорь on 31.01.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntervalOfUpdatingBusinessLogic {
    func saveIntervalOfUpdating(request: IntervalOfUpdating.SaveIntervalOfUpdating.Request)
    func getSavedIntervalOfUpdatingInSeconds()
}

class IntervalOfUpdatingInteractor: IntervalOfUpdatingBusinessLogic {
    
    var presenter: IntervalOfUpdatingPresentationLogic?
    
    // MARK: Save interval
    
    func saveIntervalOfUpdating(request: IntervalOfUpdating.SaveIntervalOfUpdating.Request) {
        UserDefaultsStorageManager.shared.saveIntervalOfUpdatingIn(seconds: request.seconds)
    }
    
    // MARK - Get saved interval
    
    func getSavedIntervalOfUpdatingInSeconds() {
        if let savedInterval = UserDefaultsStorageManager.shared.getSavedIntervalOfUpdatingInSeconds() {
            let savedTime = TimeHelper.convertSecondsToTime(seconds: savedInterval)
            let hours = savedTime.hours
            let minutes = savedTime.minutes
            let seconds = savedTime.seconds
            
            let response = IntervalOfUpdating.GetSavedIntervalOfUpdating.Response(hours: hours, minutes: minutes, seconds: seconds)
            presenter?.presentSavedIntervalOfUpdating(response: response)
        }
    }
    
}
