//
//  IntervalOfUpdatingPresenter.swift
//  News
//
//  Created by Игорь on 31.01.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntervalOfUpdatingPresentationLogic {
//    func presentSomething(response: IntervalOfUpdating.Something.Response)
}

class IntervalOfUpdatingPresenter: IntervalOfUpdatingPresentationLogic {
    
    weak var viewController: IntervalOfUpdatingDisplayLogic?
    
    // MARK: Do something
    
//    func presentSomething(response: IntervalOfUpdating.Something.Response) {
//        let viewModel = IntervalOfUpdating.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
//    }
}
