//
//  FirstTabInteractor.swift
//  News
//
//  Created by Игорь on 19.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTabBusinessLogic {
    func getSavedNewParser(request: FirstTab.GetSavedNewParser.Request)
}

protocol FirstTabDataStore {
    var feedModel: FeedModel! { get }
}

class FirstTabInteractor: FirstTabBusinessLogic, FirstTabDataStore {
    
    var presenter: FirstTabPresentationLogic?
    var worker: FirstTabWorker?
    var feedModel: FeedModel!
    
    // MARK: Do something
    
    func getSavedNewParser(request: FirstTab.GetSavedNewParser.Request) {
//        worker = FirstTabWorker()
//        worker?.doSomeWork()
        
        if let feedsModels = StorageManager.shared.getSavedFeeds(forKey: request.indexOfTab) {
            
            self.feedModel = feedsModels.first(where: { (feedModel) -> Bool in
                feedModel.isSelected
            })
            
            guard let parser = Feed.init(rawValue: feedModel.feedSource)?.parser else { return } //TODO something went wrong alert
            
            let response = FirstTab.GetSavedNewParser.Response(parser: parser)
            presenter?.getParser(response: response)
        }
    }
}
