//
//  FirstTabWorker.swift
//  News
//
//  Created by Игорь on 19.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RealmSwift

class FirstTabWorker {
    
    func saveNewsToDataBase(news: [New]) {
        
        RealmManager.addObjects(objects: news)
        
    }
    
    func getNewsFromDataBase(feedSource: String) -> [New]? {
        
        return RealmNewManager.getNewsFromDataBase(feedSource: feedSource)
        
    }
    
}
