//
//  FirstTabViewController.swift
//  News
//
//  Created by Игорь on 19.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTabDisplayLogic: class {
    func displayNews(viewModel: FirstTab.GetNews.ViewModel)
}

class FirstTabViewController: UITableViewController, FirstTabDisplayLogic {
    
    //@IBOutlet private var nameTextField: UITextField!
    @IBOutlet var navigationBar: UINavigationItem!
    
    // MARK: - Public properties
    
    var interactor: FirstTabBusinessLogic?
    var router: (NSObjectProtocol & FirstTabRoutingLogic & FirstTabDataPassing)?
    
    var parser: GenericNewsParser!
    
    // MARK: - Private properties
    
    private var news: [DisplayedNew]!
    
    //    private var feedsModels: [FeedModel]!
    //    private lazy var selectedIndexOfTab = tabBarController?.selectedIndex
    private var selectedIndex = -1
    private lazy var tabBar = tabBarController?.tabBar
    
    // MARK: Object lifecycle
    
    //    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    //        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    //        setup()
    //    }
    //
    //    required init?(coder aDecoder: NSCoder) {
    //        super.init(coder: aDecoder)
    //        setup()
    //    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        FirstTabConfigurator.shared.configure(with: self)
        
        tableView.register(UINib(nibName: "NewCell", bundle: nil), forCellReuseIdentifier: "NewCell")
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        guard let tabBar = tabBar else { return }
        guard let selectedBarItem = tabBar.selectedItem,
            let indexOfTab = tabBar.items?.firstIndex(of: (selectedBarItem)) else { return }
        
//        getSavedNewParser(indexOfTab: indexOfTab)
        
        navigationBar.title = tabBar.selectedItem?.title
        
        getNews(indexOfTab: indexOfTab)
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Display news
    
    func displayNews(viewModel: FirstTab.GetNews.ViewModel) {
        news = viewModel.news
        tableView.reloadData()
    }
    
    //MARK: - Get news
    
    func getNews(indexOfTab: Int)  {
        let request = FirstTab.GetNews.Request(indexOfTab: indexOfTab)
        interactor?.getNews(request: request)
    }
    
}

extension FirstTabViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let news = news else { return 0 }
        return news.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "NewCell", for: indexPath) as! NewCell
        
        guard let news = news else { return UITableViewCell() }
        
        cell.configure(with: news[indexPath.row])
        if selectedIndex == indexPath.row {
            cell.newTextLabel.isHidden = false
        }
        cell.selectionStyle = .none
        
        return cell
    }
    
}

extension FirstTabViewController {
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if indexPath.row == selectedIndex {
            return 120
        }
        return 60
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let cell = tableView.cellForRow(at: indexPath) as! NewCell
        if indexPath.row == selectedIndex {
            selectedIndex = -1
            cell.newTextLabel?.isHidden = true
        }else{
            selectedIndex = indexPath.row
            cell.newTextLabel?.isHidden = false
        }
        
        tableView.beginUpdates()
        tableView.endUpdates()
    }
    
    override func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {

        guard let cell = tableView.cellForRow(at: indexPath) as? NewCell else { return }
        cell.newTextLabel?.isHidden = true

    }
    
}
