//
//  FirstTabRouter.swift
//  News
//
//  Created by Игорь on 19.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FirstTabRoutingLogic {
    func routeToDetailedNew(segue: UIStoryboardSegue?)
}

protocol FirstTabDataPassing {
    var dataStore: FirstTabDataStore? { get }
}

class FirstTabRouter: NSObject, FirstTabRoutingLogic, FirstTabDataPassing {
    
    weak var viewController: FirstTabViewController?
    var dataStore: FirstTabDataStore?
    
    // MARK: Routing
    
    func routeToDetailedNew(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! DetailedNewViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetailedNew(source: dataStore!, destination: &destinationDS)
      }
    }
    
    // MARK: Passing data
    
    func passDataToDetailedNew(source: FirstTabDataStore, destination: inout DetailedNewDataStore) {
        destination.new = source.selectedNew
    }
}
