//
//  FirstTabPresenter.swift
//  News
//
//  Created by Игорь on 19.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTabPresentationLogic {
    func presentSomething(response: FirstTab.Something.Response)
}

class FirstTabPresenter: FirstTabPresentationLogic {
    
    weak var viewController: FirstTabDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: FirstTab.Something.Response) {
        let viewModel = FirstTab.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
