//
//  FirstTabPresenter.swift
//  News
//
//  Created by Игорь on 19.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstTabPresentationLogic {
    func getParser(response: FirstTab.GetSavedNewParser.Response)
}

class FirstTabPresenter: FirstTabPresentationLogic {
    
    weak var viewController: FirstTabDisplayLogic?
    
    // MARK: Return specific parser
    
    func getParser(response: FirstTab.GetSavedNewParser.Response) {
        let viewModel = FirstTab.GetSavedNewParser.ViewModel(parser: response.parser)
        viewController?.returnParser(viewModel: viewModel)
    }
}
