//
//  SourceOfNewSettingsPresenter.swift
//  News
//
//  Created by Игорь on 29.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SourceOfNewSettingsPresentationLogic {
    func presentNavigationTitle(response: SourceOfNewSettings.DisplayNavigationTitle.Response)
    func presentSourceOfNew(response: GetFeedModels)
    func presentTabBarItemTitle(response: GetTabBarItemTitleForResponse & GetNumberOfTab)
    func presentTitleOfTheNew(response: SourceOfNewSettings.UpdateTitleOfTheNew.Response)
}

class SourceOfNewSettingsPresenter: SourceOfNewSettingsPresentationLogic {
    
    weak var viewController: SourceOfNewSettingsDisplayLogic?
    
    //MARK: - Present source of new
    
    func presentSourceOfNew(response: GetFeedModels) {
        let viewModel = SourceOfNewSettings.DisplaySourceOfNew.ViewModel(feedsModels: response.feedsModels)
        viewController?.displaySourcesOfNews(viewModel: viewModel)
    }
    
    // MARK: - Present navigation title
    
    func presentNavigationTitle(response: SourceOfNewSettings.DisplayNavigationTitle.Response) {
        let navigationTitle = "Settings for \(response.numberOfTab + 1) tab"
        let viewModel = SourceOfNewSettings.DisplayNavigationTitle.ViewModel(title: navigationTitle)
        viewController?.displayNavigationTitle(viewModel: viewModel)
    }
    
    // MARK: - Present tab bar item title
    
    func presentTabBarItemTitle(response: GetTabBarItemTitleForResponse & GetNumberOfTab) {
        let viewModel: SourceOfNewSettings.SaveFeedSettings.ViewModel
        
        if let feedName = response.tabBarItemTitle {
            viewModel = SourceOfNewSettings.SaveFeedSettings.ViewModel(numberOfTab: response.numberOfTab, titleOfBar: feedName)
        } else {
            viewModel = SourceOfNewSettings.SaveFeedSettings.ViewModel(numberOfTab: response.numberOfTab, titleOfBar: "No source")
        }
        
        viewController?.displayTabBarItemTitle(viewModel: viewModel)
    }
    
    // MARK: - Present title of the new
    
    func presentTitleOfTheNew(response: SourceOfNewSettings.UpdateTitleOfTheNew.Response) {
        if response.success {
            let viewModel = SourceOfNewSettings.UpdateTitleOfTheNew.ViewModel(feeds: response.feeds, numberOfTab: response.numberOfTab, indexPathOfRow: response.indexPathfOfEditedRow)
            viewController?.displayTitleOfTheNew(viewModel: viewModel)
        } else {
            let viewModel = SourceOfNewSettings.UpdateTitleOfTheNew.ViewModel(feeds: response.feeds, numberOfTab: response.numberOfTab, indexPathOfRow: response.indexPathfOfEditedRow)
            viewController?.displayAlertTheSameTitle(viewModel: viewModel)
        }
    }
}
