//
//  SourceOfNewSettingsInteractor.swift
//  News
//
//  Created by Игорь on 29.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SourceOfNewSettingsBusinessLogic {
    func displayNavigationTitle(request: SourceOfNewSettings.DisplayNavigationTitle.Request)
    func saveFeedSettings(request: SourceOfNewSettings.SaveFeedSettings.Request)
    
    func displaySourceOfNew(request: SourceOfNewSettings.DisplaySourceOfNew.Request)
    func displayTabBarItemTitle(request: SourceOfNewSettings.DisplayTabBarItemTitle.Request)
    func selectNewSource(request: SourceOfNewSettings.SelectNewSource.Request)
    func updateTitleOfTheNew(request: SourceOfNewSettings.UpdateTitleOfTheNew.Request)
}

protocol SourceOfNewSettingsDataStore {
    var feedsModels: [FeedModel]! { get set }
    var numberOfTab: Int! { get set }
}

class SourceOfNewSettingsInteractor: SourceOfNewSettingsBusinessLogic, SourceOfNewSettingsDataStore {
    
    var presenter: SourceOfNewSettingsPresentationLogic?
    var feedsModels: [FeedModel]!
    var numberOfTab: Int!
    var indexPathOfEditedRow: IndexPath!
    
    // MARK: - Display source of new
    
    func displaySourceOfNew(request: SourceOfNewSettings.DisplaySourceOfNew.Request) {
        if let feedsModels = UserDefaultsStorageManager.shared.getSavedFeeds(forKey: numberOfTab) {
            self.feedsModels = feedsModels
        } else {
            feedsModels = Feed.allCases.map { (feed) -> FeedModel in
                FeedModel(feedName: feed.newName, feedSource: feed.url, isSelected: false)
            }
        }
        
        let response = SourceOfNewSettings.DisplaySourceOfNew.Response(feeds: feedsModels)
        presenter?.presentSourceOfNew(response: response)
    }
    
    // MARK: - Select new source
    
    func selectNewSource(request: SourceOfNewSettings.SelectNewSource.Request) {
        if let selectedIndex = feedsModels.firstIndex(where: { $0.feedName == request.feed.feedName }) {
            for index in 0..<feedsModels.count {
                feedsModels[index].isSelected = (index == selectedIndex) ? !feedsModels[index].isSelected : false
            }
        }
        
        let response = SourceOfNewSettings.SelectNewSource.Response(feedsModels: feedsModels)
        presenter?.presentSelectedNewSource(response: response)
    }
    
    //MARK: - Display tab bar title
    
    func displayTabBarItemTitle(request: SourceOfNewSettings.DisplayTabBarItemTitle.Request) {
        if let selectedFeed = feedsModels.first(where: { (feed) -> Bool in
            feed.isSelected
        }) {
            let response = SourceOfNewSettings.DisplayTabBarItemTitle.Response(numberOfTab: numberOfTab, title: selectedFeed.feedName)
            presenter?.presentTabBarItemTitle(response: response)
        }
    }
    
    // MARK: - Display navigation title
    
    func displayNavigationTitle(request: SourceOfNewSettings.DisplayNavigationTitle.Request) {
        if let numberOfTab = numberOfTab {
            let response = SourceOfNewSettings.DisplayNavigationTitle.Response(numberOfTab: numberOfTab)
            presenter?.presentNavigationTitle(response: response)
        }
    }
    
    // MARK: - Save feed settings
    
    func saveFeedSettings(request: SourceOfNewSettings.SaveFeedSettings.Request) {
        UserDefaultsStorageManager.shared.saveFeeds(feedsModels, forKey: numberOfTab)
        
        let response = SourceOfNewSettings.SaveFeedSettings.Response(feeds: feedsModels, numberOfTab: numberOfTab, indexPathfOfEditedRow: indexPathOfEditedRow)
        presenter?.presentTabBarItemTitle(response: response)
    }
    
    //MARK: - Update title of the new
    
    func updateTitleOfTheNew(request: SourceOfNewSettings.UpdateTitleOfTheNew.Request) {
        indexPathOfEditedRow = request.indexPathOfRow
        
        if let _ = feedsModels.first(where: { (feed) -> Bool in
            feed.feedName == request.feedName
        }) {
            let response = SourceOfNewSettings.UpdateTitleOfTheNew.Response(success: false, feeds: feedsModels, numberOfTab: numberOfTab, indexPathfOfEditedRow: indexPathOfEditedRow)
            presenter?.presentTitleOfTheNew(response: response)
        } else {
            feedsModels[indexPathOfEditedRow.row].feedName = request.feedName
            
            let response = SourceOfNewSettings.UpdateTitleOfTheNew.Response(success: true, feeds: feedsModels, numberOfTab: numberOfTab, indexPathfOfEditedRow: indexPathOfEditedRow)
            presenter?.presentTitleOfTheNew(response: response)
        }
    }
    
}
