//
//  SourceOfNewSettingsModels.swift
//  News
//
//  Created by Игорь on 29.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SourceOfNewSettings {
    
    // MARK: Use cases
    
    enum SelectNewSource {
        struct Request {
            let feed: FeedModel
        }
        
        struct Response {
            let feedsModels: [FeedModel]
        }
        
        struct ViewModel {
            let feedsModels: [FeedModel]
        }
    }
    
    enum DisplaySourceOfNew {
        struct Request {
        }
        
        struct Response {
            let feeds: [FeedModel]
        }
        
        struct ViewModel {
            let feedsModels: [FeedModel]
        }
    }
    
    enum Something {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
