//
//  SourceOfNewSettingsModels.swift
//  News
//
//  Created by Игорь on 29.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GetNumberOfTab {
    var numberOfTab: Int { get }
}

protocol GetTabBarItemTitleForViewModel {
    var titleOfBar: String { get }
}

protocol GetTabBarItemTitleForResponse { // TODO as above??
    var tabBarItemTitle: String? { get }
}

protocol GetFeedModels {
    var feedsModels: [FeedModel] { get }
}

enum SourceOfNewSettings {
    
    // MARK: Use cases
    
    enum SelectNewSource {
        struct Request {
            let feed: FeedModel
        }
        
        struct Response: GetFeedModels {
            let feedsModels: [FeedModel]
        }
        
        struct ViewModel: GetFeedModels {
            let feedsModels: [FeedModel]
        }
    }
    
    enum DisplaySourceOfNew {
        struct Response: GetFeedModels {
            let feedsModels: [FeedModel]
        }
        
        struct ViewModel: GetFeedModels {
            let feedsModels: [FeedModel]
        }
    }
    
    enum DisplayNavigationTitle {
        struct Response {
            let numberOfTab: Int
        }
        
        struct ViewModel {
            let title: String
        }
    }
    
    enum SaveFeedSettings {
        struct Response: GetTabBarItemTitleForResponse, GetNumberOfTab {
            let tabBarItemTitle: String?
            let numberOfTab: Int
        }
        
        struct ViewModel: GetTabBarItemTitleForViewModel, GetNumberOfTab {
            let numberOfTab: Int
            let titleOfBar: String
        }
    }
    
    enum UpdateTitleOfTheNew {
        struct Request {
            let feedName: String
            let indexPathOfRow: IndexPath
        }
        
        struct Response {
            let success: Bool
            let feeds: [FeedModel]
            let numberOfTab: Int
            let indexPathfOfEditedRow: IndexPath?
        }
        
        struct ViewModel {
            let feeds: [FeedModel]
            let numberOfTab: Int
            let indexPathOfRow: IndexPath?
        }
    }
    
    enum DisplayTabBarItemTitle {
        struct Response: GetTabBarItemTitleForResponse, GetNumberOfTab {
            let tabBarItemTitle: String?
            let numberOfTab: Int
        }
        
        struct ViewModel: GetTabBarItemTitleForViewModel, GetNumberOfTab {
            let numberOfTab: Int
            let titleOfBar: String
        }
    }
    
}
