//
//  DetailedNewRouter.swift
//  News
//
//  Created by Игорь on 17.02.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedNewDataPassing {
    var dataStore: DetailedNewDataStore? { get }
}

class DetailedNewRouter: NSObject, DetailedNewDataPassing {
    
    weak var viewController: DetailedNewViewController?
    var dataStore: DetailedNewDataStore?

}
