//
//  DetailedNewInteractor.swift
//  News
//
//  Created by Игорь on 17.02.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedNewBusinessLogic {
    func getSelectedNew()
}

protocol DetailedNewDataStore {
    var new: New! { get set }
}

class DetailedNewInteractor: DetailedNewBusinessLogic, DetailedNewDataStore {
    
    var presenter: DetailedNewPresentationLogic?
    
    var new: New!
    
    // MARK: Get selected new
    
    func getSelectedNew() {
        let response = DetailedNew.DisplaySelectedNew.Response(new: new)
        presenter?.presentSelectedNew(response: response)
    }
}
