//
//  DetailedNewWorker.swift
//  News
//
//  Created by Игорь on 17.02.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailedNewWorker {
    func doSomeWork() {
    }
}
