//
//  DetailedNewViewController.swift
//  News
//
//  Created by Игорь on 17.02.2020.
//  Copyright (c) 2020 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedNewDisplayLogic: class {
    func displaySelectedNew(viewModel: DetailedNew.DisplaySelectedNew.ViewModel)
}

class DetailedNewViewController: UIViewController, DetailedNewDisplayLogic {
    
    // MARK: - @IBOutlets
    
    @IBOutlet var imageOfNew: UIImageView!
    @IBOutlet var titleOfNew: UITextView!
    @IBOutlet var descriptionOfNew: UITextView!
    
    // MARK: - Public properties
    
    var interactor: DetailedNewBusinessLogic?
    var router: (NSObjectProtocol & DetailedNewRoutingLogic & DetailedNewDataPassing)?
    
    // MARK: Object lifecycle
    
//    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
//        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
//        setup()
//    }
//
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        DetailedNewConfigurator.shared.configure(with: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureView()
        
        interactor?.getSelectedNew()
        
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Display selected new
    
    func displaySelectedNew(viewModel: DetailedNew.DisplaySelectedNew.ViewModel) {
        let new = viewModel.new
        imageOfNew.fetchImage(with: new.imageRef)
        titleOfNew.text = new.title
        descriptionOfNew.text = new.descripton
    }
    
    // MARK: - Private methods
    
    private func configureView() {
        
        view.backgroundColor = Constants.Colors.backGroundColor
        
        imageOfNew.layer.cornerRadius = 5
        
        titleOfNew.font               = Constants.Fonts.titleTextFontSize
        titleOfNew.textColor          = Constants.Colors.titleTextColor
        
        descriptionOfNew.font         = Constants.Fonts.mainTextDetailedNewFontSize
        descriptionOfNew.textColor    = Constants.Colors.mainTextColor
        
    }
    
}
