//
//  TabSettingsRouter.swift
//  News
//
//  Created by Игорь on 26.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TabSettingsRoutingLogic {
    func routeToSourceOfNewSettings(segue: UIStoryboardSegue?)
}

protocol TabSettingsDataPassing {
    var dataStore: TabSettingsDataStore? { get }
}

class TabSettingsRouter: NSObject, TabSettingsRoutingLogic, TabSettingsDataPassing {
    
    weak var viewController: TabSettingsViewController?
    var dataStore: TabSettingsDataStore?
    
    // MARK: Routing
    
    func routeToSourceOfNewSettings(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! SourceOfNewSettingsViewController
        var destinationDS = destinationVC.router!.dataStore!
        let sourceVC = segue.source as! TabSettingsViewController
        destinationDS.delegate = sourceVC.interactor
        passDataToSourceOfNewSettings(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "SourceOfNewSettingsViewController") as! SourceOfNewSettingsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSourceOfNewSettings(source: dataStore!, destination: &destinationDS)
        navigateToSourceOfNewSettings(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToSourceOfNewSettings(source: TabSettingsViewController, destination: SourceOfNewSettingsViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSourceOfNewSettings(source: TabSettingsDataStore, destination: inout SourceOfNewSettingsDataStore) {
        destination.numberOfTab = source.numberOfTab
    }
}
