//
//  TabSettingsPresenter.swift
//  News
//
//  Created by Игорь on 26.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabSettingsPresentationLogic {
    func presentNavigationTitle(response: TabSettings.DisplayNavigationTitle.Response)
    func presentNameOfTheSourceNew(response: TabSettings.DisplayNameOfTheNew.Response)
}

class TabSettingsPresenter: TabSettingsPresentationLogic {
    
    
    
    weak var viewController: TabSettingsDisplayLogic?
    
    // MARK: - Present anvigation title
    
    func presentNavigationTitle(response: TabSettings.DisplayNavigationTitle.Response) {
        let navigationTitle = "Settings for \(response.numberOfTab + 1) tab"
        let viewModel = TabSettings.DisplayNavigationTitle.ViewModel(title: navigationTitle)
        viewController?.displayNavigationTitle(viewModel: viewModel)
    }
    
    // MARK: - Present name of the source new
    
    func presentNameOfTheSourceNew(response: TabSettings.DisplayNameOfTheNew.Response) {
        let viewModel = TabSettings.DisplayNameOfTheNew.ViewModel(feedName: response.feedName)
        viewController?.displayNameOfTheNewSource(viewModel: viewModel)
    }
}
