//
//  TabSettingsViewController.swift
//  News
//
//  Created by Игорь on 26.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabSettingsDisplayLogic: class {
    func displayNavigationTitle(viewModel: TabSettings.DisplayNavigationTitle.ViewModel)
    func displayNameOfTheNewSource(viewModel: TabSettings.DisplayNameOfTheNew.ViewModel)
}

class TabSettingsViewController: UITableViewController, TabSettingsDisplayLogic {
    
    // MARK: - IBOutlets
    
    @IBOutlet var nameOfTheNewTextField: UITextField!
    
    // MARK: - Public properties
    
    var interactor: TabSettingsBusinessLogic?
    var router: (NSObjectProtocol & TabSettingsRoutingLogic & TabSettingsDataPassing)?
    
    
    // MARK: - Object lifecycle
    
    //    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    //        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    //        setup()
    //    }
    //
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        TabSettingsConfigurator.shared.configure(with: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        displayNavigationTitle()
        interactor?.displayNameOfTheSourceNew()
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - Display navigation title
    
    func displayNavigationTitle() {
        let request = TabSettings.DisplayNavigationTitle.Request()
        interactor?.displayNavigationTitle(request: request)
    }
    
    //TODO - bug needs to be fixed
    
    func displayNavigationTitle(viewModel: TabSettings.DisplayNavigationTitle.ViewModel) {
        navigationItem.title = viewModel.title
    }
    
    // MARK: - Display name of the new source
    
    func displayNameOfTheNewSource(viewModel: TabSettings.DisplayNameOfTheNew.ViewModel) {
        nameOfTheNewTextField.text = viewModel.feedName
    }
    
    // MARK: - IBActions
    
    @IBAction func saveButtonPressed() {
        interactor?.saveFeedSettings()
        interactor?.displayNameOfTheSourceNew()
    }
    
}

extension TabSettingsViewController {
    
    // MARK: - Tableview elegate methods
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        performSegue(withIdentifier: "SourceOfNewSettings", sender: nil)
    }
    
}
