//
//  TabSettingsModels.swift
//  News
//
//  Created by Игорь on 26.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TabSettings {
    
    // MARK: - Use cases
    
    enum DisplayNavigationTitle {
        struct Request {
        }
        
        struct Response {
            let numberOfTab: Int
        }
        
        struct ViewModel {
            let title: String
        }
    }
    
//    enum SaveFeedSettings {
//        struct Request {
//        }
//
//        struct Response {
//        }
//
//        struct ViewModel {
//        }
//    }
    
    enum DisplayNameOfTheNew {
        struct Request {
        }
        
        struct Response {
            let feedName: String
        }
        
        struct ViewModel {
            let feedName: String
        }
    }
    
}
