//
//  SettingsPresenter.swift
//  News
//
//  Created by Игорь on 27.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
    func presentSwitcherValue(response: Settings.GetSwitcherValue.Response)
}

class SettingsPresenter: SettingsPresentationLogic {
    
    weak var viewController: SettingsDisplayLogic?
    
    // MARK: Present switcher value
    
    func presentSwitcherValue(response: Settings.GetSwitcherValue.Response) {
        let viewModel = Settings.GetSwitcherValue.ViewModel(isOn: response.isOn)
        viewController?.displaySwitcherValue(viewModel: viewModel)
    }
}
