//
//  SettingsPresenter.swift
//  News
//
//  Created by Игорь on 27.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
    func presentSomething(response: Settings.SelectTab.Response)
}

class SettingsPresenter: SettingsPresentationLogic {
    
    weak var viewController: SettingsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Settings.SelectTab.Response) {
        let viewModel = Settings.SelectTab.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
