//
//  SettingsInteractor.swift
//  News
//
//  Created by Игорь on 27.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic {
    func selectTab(request: Settings.SelectTab.Request)
}

protocol SettingsDataStore {
    var numberOfTab: Int! { get }
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore {
    
    var presenter: SettingsPresentationLogic?
    var worker: SettingsWorker?
    
    var numberOfTab: Int!
    
    // MARK: Do something
    
    func selectTab(request: Settings.SelectTab.Request) {
        numberOfTab = request.numberOfTab
    }
}
