//
//  SettingsModels.swift
//  News
//
//  Created by Игорь on 27.12.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {
    
    // MARK: - Use cases
    
    enum SelectTab {
        
        struct Request {
            let numberOfTab: Int
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
